### PR TITLE
Added Java 12 support

### PR DESCRIPTION
**Pull request by MrSandmanRUS**
#130 issue fix.
Added Java 12 support on startup.

### CODE REVIEW

**Comment by stokito** [comment]
Thank you for the PR. How about not limiting upper JDK version at all? When JDK13 will be released I'm pretty sure that VisualVM will work too.

**Comment by MrSandmanRUS** [comment]
@stokito 
I'm not sure what the next versions will be. What if version 13 is released and then version 15 is released? In principle, we can now check that the version is 1.8, or 1.9, or >=9. What do you think about it @thurka @jisedlac ? If it's OK, I can add that.

**Comment by stokito** [comment]
TBH it doesn't matter: we can only clearly say that this JDK is too old and not supported but any newer JDK  will be supported unless it keeps a backward compatibility.

**Comment by MrSandmanRUS** [comment]
> TBH it doesn't matter: we can only clearly say that this JDK is too old and not supported but any newer JDK will be supported unless it keeps a backward compatibility.

Ok, added support for JDK 8 or higher.

**Pull request closed without merging**
